name: TodoApp CI with maven

on:
  push:
    branches: ["main", "dev", "prod-support"]
  pull_request:
    branches: ["main", "dev", "prod-support"]

jobs:
  build:
    name: Application Build
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4
      - name: set uo JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Maven Package
        run: mvn -B clean package

